












services:
  - type: web
    name: indicadorhse6
    env: node
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
